# ============================================================
# Primary aim model diagnostics and sensitivity analyses
# For models generated by Primary_aim_analysis_robustSE.R
# ============================================================

library(car)
library(ggplot2)
library(lmtest)
library(sandwich)

# ------------------------------------------------------------
# 1. Load saved models and exact data used to fit them
# ------------------------------------------------------------

m_primary <- readRDS("m_primary_results.RDS")
m_delta   <- readRDS("m_delta_results.RDS")

m_primary_data_used <- readRDS("m_primary_data_used.RDS")
m_delta_data_used   <- readRDS("m_delta_data_used.RDS")

# ------------------------------------------------------------
# 2. Robust standard error helper (HC3)
# ------------------------------------------------------------

get_robust_results <- function(model, model_name) {
  vcov_hc3 <- sandwich::vcovHC(model, type = "HC3")
  robust_test <- lmtest::coeftest(model, vcov. = vcov_hc3)
  robust_ci <- lmtest::coefci(model, vcov. = vcov_hc3)

  data.frame(
    model = model_name,
    term = rownames(robust_test),
    estimate = robust_test[, "Estimate"],
    robust_se = robust_test[, "Std. Error"],
    statistic = robust_test[, "t value"],
    p_value = robust_test[, "Pr(>|t|)"],
    ci_lower = robust_ci[, 1],
    ci_upper = robust_ci[, 2],
    row.names = NULL
  )
}

# ------------------------------------------------------------
# 3. Helper function for diagnostics
# ------------------------------------------------------------

run_model_diagnostics <- function(model, model_name, model_data) {
  fitted_vals <- fitted(model)
  resid_vals  <- resid(model)
  std_resid   <- rstandard(model)
  stud_resid  <- rstudent(model)
  cooks       <- cooks.distance(model)
  leverage    <- hatvalues(model)

  n <- nobs(model)
  p <- length(coef(model)) - 1

  cook_cutoff <- 4 / n
  lev_cutoff  <- 2 * (p + 1) / n

  shapiro_out <- shapiro.test(resid_vals)
  bp_out      <- car::ncvTest(model)
  vif_vals    <- car::vif(model)
  robust_results <- get_robust_results(model, model_name)

  diagnostics_summary <- data.frame(
    model = model_name,
    n = n,
    shapiro_W = unname(shapiro_out$statistic),
    shapiro_p = shapiro_out$p.value,
    breusch_pagan_chisq = unname(bp_out$ChiSquare),
    breusch_pagan_p = bp_out$p,
    max_abs_std_resid = max(abs(std_resid), na.rm = TRUE),
    max_abs_stud_resid = max(abs(stud_resid), na.rm = TRUE),
    max_cooks_distance = max(cooks, na.rm = TRUE),
    n_cooks_above_cutoff = sum(cooks > cook_cutoff, na.rm = TRUE),
    max_leverage = max(leverage, na.rm = TRUE),
    n_leverage_above_cutoff = sum(leverage > lev_cutoff, na.rm = TRUE)
  )

  vif_table <- data.frame(
    model = model_name,
    predictor = names(vif_vals),
    vif = as.numeric(vif_vals)
  )

  influence_table <- data.frame(
    athlete = model_data$athlete,
    observation = seq_len(n),
    fitted = fitted_vals,
    residual = resid_vals,
    std_resid = std_resid,
    stud_resid = stud_resid,
    cooks_distance = cooks,
    leverage = leverage,
    cooks_flag = cooks > cook_cutoff,
    leverage_flag = leverage > lev_cutoff,
    std_resid_flag = abs(std_resid) > 2
  )

  png(
    filename = paste0(gsub(" ", "_", tolower(model_name)), "_diagnostic_plots.png"),
    width = 1200, height = 1200, res = 130
  )
  par(mfrow = c(2, 2))
  plot(model)
  dev.off()

  png(
    filename = paste0(gsub(" ", "_", tolower(model_name)), "_residual_normality.png"),
    width = 1000, height = 450, res = 130
  )
  par(mfrow = c(1, 2))
  hist(resid_vals,
       main = paste(model_name, "- Residual histogram"),
       xlab = "Residuals",
       col = "grey80",
       border = "white")
  qqnorm(resid_vals,
         main = paste(model_name, "- Normal Q-Q plot"),
         pch = 19,
         col = "black")
  qqline(resid_vals, col = "red", lwd = 2)
  dev.off()

  png(
    filename = paste0(gsub(" ", "_", tolower(model_name)), "_influence_plots.png"),
    width = 1000, height = 450, res = 130
  )
  par(mfrow = c(1, 2))
  plot(cooks, type = "h",
       main = paste(model_name, "- Cook's distance"),
       xlab = "Observation",
       ylab = "Cook's distance")
  abline(h = cook_cutoff, col = "red", lty = 2)

  plot(leverage, std_resid,
       main = paste(model_name, "- Leverage vs std residuals"),
       xlab = "Leverage",
       ylab = "Standardised residuals",
       pch = 19,
       col = ifelse(leverage > lev_cutoff | abs(std_resid) > 2, "red", "black"))
  abline(v = lev_cutoff, col = "red", lty = 2)
  abline(h = c(-2, 2), col = "red", lty = 2)
  dev.off()

  list(
    summary = diagnostics_summary,
    vif = vif_table,
    influence = influence_table,
    robust = robust_results
  )
}

# ------------------------------------------------------------
# 4. Run diagnostics on both models
# ------------------------------------------------------------

diag_primary <- run_model_diagnostics(m_primary, "Primary model", m_primary_data_used)
diag_delta   <- run_model_diagnostics(m_delta, "Delta model", m_delta_data_used)

diagnostics_summary <- rbind(
  diag_primary$summary,
  diag_delta$summary
)

vif_results <- rbind(
  diag_primary$vif,
  diag_delta$vif
)

influence_results <- rbind(
  transform(diag_primary$influence, model = "Primary model"),
  transform(diag_delta$influence, model = "Delta model")
)

robust_results_all <- rbind(
  diag_primary$robust,
  diag_delta$robust
)

cat("
================ DIAGNOSTICS SUMMARY ================
")
print(diagnostics_summary)

cat("
================ VIF RESULTS ================
")
print(vif_results)

cat("
================ ROBUST RESULTS (HC3) ================
")
print(robust_results_all)

cat("
================ FLAGGED OBSERVATIONS ================
")
print(subset(influence_results, cooks_flag | leverage_flag | std_resid_flag))

# ------------------------------------------------------------
# 5. Sensitivity analyses with robust standard errors
# ------------------------------------------------------------

flagged_primary <- subset(
  diag_primary$influence,
  cooks_flag | leverage_flag | std_resid_flag
)

influential_athletes <- unique(as.character(flagged_primary$athlete))

cat("
================ INFLUENTIAL ATHLETES =================
")
print(influential_athletes)

primary_formula <- formula(m_primary)

sensitivity_results <- list()

for (ath in influential_athletes) {
  data_excl <- subset(m_primary_data_used, athlete != ath)
  refit <- lm(primary_formula, data = data_excl)

  robust_refit <- get_robust_results(refit, paste0("Primary model excluding ", ath))
  robust_refit$excluded_athlete <- ath

  sensitivity_results[[ath]] <- robust_refit
}

if (length(sensitivity_results) > 0) {
  sensitivity_results_df <- do.call(rbind, sensitivity_results)

  sensitivity_summary <- subset(sensitivity_results_df, term != "(Intercept)")
  sensitivity_summary <- aggregate(
    cbind(estimate, ci_lower, ci_upper) ~ term,
    data = sensitivity_summary,
    FUN = function(x) c(min = min(x, na.rm = TRUE), max = max(x, na.rm = TRUE))
  )

  sensitivity_summary <- data.frame(
    term = sensitivity_summary$term,
    estimate_min = sensitivity_summary$estimate[, "min"],
    estimate_max = sensitivity_summary$estimate[, "max"],
    ci_lower_min = sensitivity_summary$ci_lower[, "min"],
    ci_lower_max = sensitivity_summary$ci_lower[, "max"],
    ci_upper_min = sensitivity_summary$ci_upper[, "min"],
    ci_upper_max = sensitivity_summary$ci_upper[, "max"],
    row.names = NULL
  )

  coef_ranges <- subset(sensitivity_results_df, term != "(Intercept)")
  sign_summary <- aggregate(
    estimate ~ term,
    data = coef_ranges,
    FUN = function(x) {
      if (any(x < 0, na.rm = TRUE) & any(x > 0, na.rm = TRUE)) {
        "Changed sign"
      } else if (all(x < 0, na.rm = TRUE)) {
        "Always negative"
      } else if (all(x > 0, na.rm = TRUE)) {
        "Always positive"
      } else {
        "Mixed/unclear"
      }
    }
  )

  sensitivity_summary <- merge(sensitivity_summary, sign_summary, by = "term", all.x = TRUE)
  names(sensitivity_summary)[names(sensitivity_summary) == "estimate"] <- "direction_stability"

  cat("
================ SENSITIVITY ANALYSIS SUMMARY (ROBUST SE) ================
")
  print(sensitivity_summary)

  write.csv(sensitivity_results_df, "primary_model_sensitivity_results_robustSE.csv", row.names = FALSE)
  write.csv(sensitivity_summary, "primary_model_sensitivity_summary_robustSE.csv", row.names = FALSE)
} else {
  cat("
No influential athletes were flagged in the primary model, so no sensitivity analyses were run.
")
}

# ------------------------------------------------------------
# 6. Save outputs
# ------------------------------------------------------------

write.csv(diagnostics_summary, "model_diagnostics_summary.csv", row.names = FALSE)
write.csv(vif_results, "model_vif_results.csv", row.names = FALSE)
write.csv(influence_results, "model_influence_results.csv", row.names = FALSE)
write.csv(robust_results_all, "model_robust_results_HC3.csv", row.names = FALSE)

cat("
Saved files:
")
cat("- model_diagnostics_summary.csv
")
cat("- model_vif_results.csv
")
cat("- model_influence_results.csv
")
cat("- model_robust_results_HC3.csv
")
cat("- primary_model_diagnostic_plots.png
")
cat("- primary_model_residual_normality.png
")
cat("- primary_model_influence_plots.png
")
cat("- delta_model_diagnostic_plots.png
")
cat("- delta_model_residual_normality.png
")
cat("- delta_model_influence_plots.png
")
if (exists("sensitivity_results_df")) {
  cat("- primary_model_sensitivity_results_robustSE.csv
")
  cat("- primary_model_sensitivity_summary_robustSE.csv
")
}

